// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsBQTj5iSr0n8omDyqoI0jLyV_cErZ6sY',
    appId: '1:1097210691897:web:396bceaf42c89c48f728e8',
    messagingSenderId: '1097210691897',
    projectId: 'cipherx-59e10',
    authDomain: 'cipherx-59e10.firebaseapp.com',
    storageBucket: 'cipherx-59e10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-A10Ntw2nzGeB765k1R7u6_iFna7Sl0',
    appId: '1:1097210691897:android:e28d4fdbfbec9306f728e8',
    messagingSenderId: '1097210691897',
    projectId: 'cipherx-59e10',
    storageBucket: 'cipherx-59e10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7eXgblWDIptpRgIXGA7_QSfzoFox9QQA',
    appId: '1:1097210691897:ios:7b78d29a9a4a8098f728e8',
    messagingSenderId: '1097210691897',
    projectId: 'cipherx-59e10',
    storageBucket: 'cipherx-59e10.appspot.com',
    iosBundleId: 'com.example.cipherx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7eXgblWDIptpRgIXGA7_QSfzoFox9QQA',
    appId: '1:1097210691897:ios:e2b4a4cab888858bf728e8',
    messagingSenderId: '1097210691897',
    projectId: 'cipherx-59e10',
    storageBucket: 'cipherx-59e10.appspot.com',
    iosBundleId: 'com.example.cipherx.RunnerTests',
  );
}
